version: "3.8"

services:
  # postgres:
  #   image: postgres:15
  #   container_name: chainhunter-postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: chaindb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: app.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://python_backend:8000
    depends_on:
      - postgres
      - python_backend

  python_backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DEEPSEEK_API_BASE=${DEEPSEEK_API_BASE}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    command: ["python", "main.py"]
    depends_on:
      - postgres

volumes:
  postgres_data:
